### ISSUE TITLE
Linker error: framework not found Crashlytics

### ISSUE THREAD

**Issue by andreyz** [TechSmith/CrashlyticsLumberjack#9]
I'm building CrashlyticsLumberjack as a framework using CocoaPods `use_frameworks!` option. Unfortunately the build fails with:
```
ld: framework not found Crashlytics
```
Any ideas what is going on there?

P.S. Thanks for a great and useful library!

**Comment by waltflanagan** [comment]
Thanks for the report.   It looks like this is an issue with how Cocoapods is building frameworks now.  I'll look into how I could get this working as a framework, but right now it seems like the quickest solution is to introduce a dependency on the CrashlyticsFramework pod.   I don't really like that solution since most people install crashlytics through the app.

I'll try to find a way to make it so this pod can link against a framework within the main project.

**Comment by andreyz** [comment]
Thanks @waltflanagan! I thought so too that new CocoaPods feature and Fabric's bundled Crashlytics framework is to blame here.

**Comment by neonichu** [comment]
The issue here is that using `spec.framework` when integrating frameworks will link against the pod target instead of the user target. The pods project doesn't know about the Crashlytics framework from the main project, though.

You could amend the `FRAMEWORKS_SEARCH_PATH` in your podspec via `spec.xcconfig` - if the path to the Crashlytics frameworks is well-known. 

Another solution and a temporary workaround is amending the `FRAMEWORKS_SEARCH_PATH` in the individual Podfile:

```
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
    	if not config.build_settings['FRAMEWORK_SEARCH_PATHS']
    		config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ['$(inherited)']
      end

      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '"$(SRCROOT)/.."'
    end
  end
end
```

**Comment by andreyz** [comment]
@neonichu thank you, but your temporary workaround doesn't seem to work for me.

I've also tried using Fabric & Crashlytics frameworks via [CocoaPod](https://github.com/zergtmn/Fabric) instead of the ones provided by Fabric app.

Build still fails with `ld: framework not found Crashlytics`.

**Comment by neonichu** [comment]
@andreyz This assumes the following structure:

```
.
├── Crashlytics.framework
├── Pods
│   ├── Pods.xcodeproj
```

If your `Crashlytics.framework` is located somewhere else, you have to adjust the relative path accordingly (`$(SRCROOT)/..` in the example workaround).

**Comment by andreyz** [comment]
@neonichu thanks! Fabric CocoaPod places Crashlytics.framework under Pods/Fabric/, so I just needed to adjust your workaround to point to `$(SRCROOT)/Fabric`.

Now I'm hitting a new issue though:
```
Undefined symbols for architecture arm64:
  "_CLSLog", referenced from:
      -[CrashlyticsLogger logMessage:] in CrashlyticsLogger.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by waltflanagan** [comment]
im working on getting a 2.0.1-beta spec pushed that should at least allow you to continue working.  

It will have a subspec for framework usage that requires the CrashlyticsFramework pod.   This will likely conflict with any previous installs of Crashlytics or Fabric.

It looks like the Fabric podspec also doesnt play well with frameworks in cocoapods: 
[!] The 'Pods' target has transitive dependencies that include static binaries: (~/Code/PodsTest/Pods/Fabric/Fabric.framework)

**Comment by waltflanagan** [comment]
I just pushed the new podspec, it will be live soon*

**Comment by andreyz** [comment]
@waltflanagan thanks!
